title: Rapid Time Tracker
description: An ultra-lightweight time tracker operating on a local text file.
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
- jekyll-sitemap